MuzMusic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from .error_views import handler404, handler500, handler400, handler403  # Import directly from the main project



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('account.urls')),


]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)






# handler404 = handler404  # Set the error handlers
# handler500 = handler500
# handler400 = handler400
# handler403 = handler403

blog/urls.py
from django.urls import path
from .views import BlogSingleView,BasePostListView,BlogAuthorView,BlogCategoryView,BlogHomeView,likeView,PostCreateView,follow_unfollow

app_name='blog'

urlpatterns = [
   # path('',BlogView.as_view(),name='blog_view'),
    path('single-view/<int:pk>',BlogSingleView.as_view(), name='single_view'),
    path('category/<str:cat_name>/', BlogCategoryView.as_view(), name='blog_category'),
    path('author/<str:author_name>/', BlogAuthorView.as_view(), name='blog_author'),
    path('', BlogHomeView.as_view(), name='blog_home'),
        # This will handle the default case with pagination
    path('like/<int:pk>',likeView, name='like_post'),
    path('post-create',PostCreateView.as_view(),name='post_create'),
    path('follow-unfollow',follow_unfollow,name='follow')
   ]

website/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import IndexView,DetailedAboutView,ContactView,PrimaryAboutView

app_name='website'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/<str:cat_name>', DetailedAboutView.as_view(),name='detailed_about'),
    path('about', PrimaryAboutView.as_view(),name='about'),
    path('contact', ContactView.as_view(),name='contact'),
    

]

website/models.py
from django.db import models
# Create your models here.

choices=[('music','music'),('programming','programming'),('life','life'),('studies','studies')]
class Maziar(models.Model):
    title=models.CharField(max_length=120)
    content=models.TextField()
    category=models.CharField(max_length=40,choices=choices,default='music')
    image_file=models.ImageField(null=True,blank=True)
    video_file=models.FileField(null=True,blank=True)
    audio_file=models.FileField(null=True,blank=True)
    created=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

website/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Enter your name',
                                                                       'class': 'common-input mb-20 form-control',
                                                                       'onfocus': "this.placeholder = ''",
                                                                       'onblur': "this.placeholder = 'Enter your name'"
                                                                       }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter email address',
                                                          'pattern': "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{1,63}$",
                                                          'class': 'common-input mb-20 form-control',
                                                          'onfocus': "this.placeholder = ''",
                                                          'onblur': "this.placeholder = 'Enter email address'"
                                                          }))
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Enter subject',
                                                                         'class': 'common-input mb-20 form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Enter your message',
                                                                       'class': 'common-input mb-20 form-control',
                                                                       'onfocus': "this.placeholder = ''",
                                                                       'onblur': "this.placeholder = 'Enter your message'"}))
    

website/views.py
from django.shortcuts import render,redirect
from account.models import Profile
from .models import Maziar
from .forms import ContactForm
from django.urls import reverse_lazy,reverse
from django.core.mail import send_mail,EmailMultiAlternatives
from django.views.generic import TemplateView,ListView,FormView
from blog.forms import FollowForm
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from utils import follow_unfollow
from decouple import config



class IndexView(TemplateView):
    template_name = 'website/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Fetch random profiles to display
        if self.request.user.is_authenticated:
            context['random_profiles'] = Profile.objects.exclude(user=self.request.user).order_by('?')
        else:
            context['random_profiles'] = Profile.objects.all().order_by('?')
   
        context['follow_form'] = FollowForm()
        return context
    
    def post(self, request, *args, **kwargs):
        form = FollowForm(request.POST)
        if form.is_valid():
            target_profile_id = form.cleaned_data['target_profile_id']
            current_user_profile = request.user.profile  # Assuming there's a one-to-one relation
            target_profile = Profile.objects.get(id=target_profile_id)
            follow_unfollow(current_user_profile, target_profile)
            # sometimes i dont understand difference between the obj and its id
            return redirect('website:index')  # Redirect back to the index page

        return self.get(request, *args, **kwargs)
# im kinda feeling code smell for habdling the unuthorized user in the index page
# i am adding condidtions for the random_profiles and i am creating a fake follow buttom
# for the unauthorized user to be taken to the login page




class PrimaryAboutView(TemplateView):
    template_name='website/about.html'



class DetailedAboutView(ListView):
    model=Maziar
    template_name='website/about.html'
    context_object_name= 'maziars'
    def get_queryset(self):

        queryset=super().get_queryset()
        for a in queryset:
            print(a.category)
        cat_name = self.kwargs.get('cat_name')
        print(cat_name)
        if cat_name:
            queryset = queryset.filter(category=cat_name)
            print(queryset)
        return queryset    




class ContactView(FormView):
    template_name = 'website/contact.html'
    form_class = ContactForm
    success_url= reverse_lazy('website:index')

    def form_valid(self, form):
        # This method is called when the form is valid
        name = form.cleaned_data.get('name')
        email = form.cleaned_data.get('email')
        subject = form.cleaned_data.get('subject')
        user_message = form.cleaned_data.get('message')

        # Send the email
        send_mail(subject,
                  user_message,
                  email,
                  [config('EMAIL')],
                  fail_silently=False)
        

       
        context= {
                'name':name,
            }
          
        html_message=render_to_string('website/new-email_2024-08-04T081801.251673.html',context=context)
        plain_message= strip_tags(html_message)
        message=EmailMultiAlternatives(subject='Message Received',body=plain_message,from_email='maziarheidari1124@gmail.com',
                    to=[email] 
                    )
        message.attach_alternative(html_message,'text/html')
        message.send()
            

        # Return the success URL
        return super().form_valid(form)

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
		
<style>
    video {
        width: 100%;
        height: auto;
    }
</style>
			<!-- start banner Area -->
			<section class="about-banner relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								About Us(Maziar!)				
							</h1>	
						</div>	
					</div>
				</div>
			</section>
			

			<section class="about-info-area section-gap">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 info-left">
							<img style="width: 90%; height: 90%;" class="img-fluid" src="{% static 'images/maziar.jpg' %}" alt="">
							
						</div>
						<div class="col-lg-6 info-right">
							<h6>Maziar the Author:</h6>
							<h1>Its Maziar Heidary Speaking:</h1>
							<p>
								I dont't really knpw what to say. Having an about page was the hardest part of this project!
								To summerize. I'm hardworking and ontime person, so eager to learn and as the big man Steve Jobs said,
								I'm foolish, I'm crazy
							</p>
						</div>
					</div>
				</div>	
			</section>

			{% for maziar in maziars %}
			<section class="about-info-area section-gap">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 info-left">
							{% if maziar.image_file %}

							<img  class="img-fluid" src="{{maziar.image_file.url}}" alt="">
							{% endif %}
							
							{% if maziar.video_file %}
							<video style="vertical-align: middle;max-width: 100%;height: auto; border-style: none;" class="img-fluid" controls style="width: 50%; height: 50%;">
								<source src="{{ maziar.video_file.url }}" type="video/mp4">
								<source src="{{ maziar.video_file.url }}" type="video/ogg">
								Your browser does not support embedded video.
								</video>
								
							{% endif %}
						</div>
						<div class="col-lg-6 info-right">
							<h6>Maziar the Author:</h6>
							<h1>{{maziar.title}}</h1>
							<p>
								{{maziar.content}}
							</p>
						</div>
					</div>
				</div>	
			</section>
			{% endfor %}
			<!-- End about-info Area -->
			
			<!-- Start other-issue Area -->
			<section class="other-issue-area section-gap">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="menu-content pb-70 col-lg-9">
							<div class="title text-center">
								<h1 class="mb-10">Who Am I? Computer, Music, Working, Studies, Life...</h1>
								<p>Not a man to wasts words! Lets see what I've got gere!</p>
							</div>
						</div>
					</div>					
					<div class="row">
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" style="width: 245; height: 155px; object-fit: cover; " src="{% static 'images/amir_darabi.jpg' %}" alt="">					
								</div>
								<a href="{% url 'website:detailed_about' cat_name='music'  %}">
									<h4>Music</h4>
								</a>
								<p>
									Well I'm really into music and believe it or not if I could feel safe living a musician life, I would've put all of my effort only in this feild.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img style="height: 80%; object-fit: cover;" class="img-fluid" src="{% static 'images/_4th_cover.png' %}" alt="">					
								</div>
								<a href="{% url 'website:detailed_about' cat_name='programming' %}">
									<h4>Programming and Projects</h4>
								</a>
								<p>
									I'm really into Django and python these days. So eager to learn looking for a good path to grow! 
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'images/life.jpg' %}" alt="">					
								</div>
								<a href="{% url 'website:detailed_about' cat_name='life' %}">
									<h4>Life is not Beautiful!</h4>
								</a>
								<p>
									It's a meaningless life no matter you are Maziar or Steve Jobs. So what the heck am I doning here palnning and learning skills? For what?!
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'images/daneshgah.jpg' %}" alt="">					
								</div>
								<a href="{% url 'website:detailed_about' cat_name='studies' %}">
									<h4>University</h4>
								</a>
								<p>
									I'm studying Computer Engineering at Shiraz University of Technology, I don't really have good memories of studying but again Life goes on!
								</p>
							</div>
						</div>																		
					</div>
				</div>	
			</section>
			<!-- End other-issue Area -->

		{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}

{% load static %}

	{% block content %}
	  
			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Contact Us				
							</h1>	
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start contact-page Area -->
			<section class="contact-page-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-4 d-flex flex-column address-wrap">
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-home"></span>
								</div>
								<div class="contact-details">
									<h5>Pasdaran, Shiraz</h5>
									<p>
										Just say my name! You will find me!
									</p>
								</div>
							</div>
						
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-envelope"></span>
								</div>
								<div class="contact-details">
									<h5>maziarheidari1124@gmail.com</h5>
									<p>Send an email! Whatever! Anytime!</p>
								</div>
							</div>														
						</div>
						<div class="col-lg-8">
							
							
							 <form method="POST" class="form-area contact-form text-right"  action="" >
								{% csrf_token %}
								<div class="row">	
									<div class="col-lg-6 form-group">
										{% if not request.user.is_authenticated %}
										{{form.name}}
										{{form.email}}

										
										{% else %}
											<input type="hidden" name="name" value="{{request.user.first_name}}">
											<input type="hidden" name="email" value="{{request.user.email}}">

										{% endif %}
										{{form.subject}}
									</div>
									<div class="col-lg-6 form-group">
										{{form.message}}
									</div>
									<div class="col-lg-12">
										<div class="alert-msg" style="text-align: left;"></div>
										<button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>											
									</div>
								</div>
							</form>	 
						</div>
					</div>
				</div>	
			</section>
			<!-- End contact-page Area -->

		{% endblock %}

templates/website/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

		<!-- start banner Area -->
		<section class="banner-area relative">
			<div class="overlay overlay-bg"></div>				
			<div class="container">
				<div class="row fullscreen align-items-center justify-content-between">
					<div class="col-lg-6 col-md-6 banner-left">
						<h1 class="text-white">Welcome to MuzMusic</h1>
						<p class="text-white">
							You into music? Or looking for some cool frends? Or you you wanna get to know Maziar?! Come on sign in and let us know you!
						</p>
						
					</div>
					
				</div>
			</div>					
		</section>
		<!-- End banner Area -->

	

		<!-- Start other-issue Area -->
		<section class="other-issue-area section-gap">
			<div class="container">
				<div class="row d-flex justify-content-center">
					<div class="menu-content pb-70 col-lg-9">
						<div class="title text-center">
							<h1 class="mb-10">Who Am I? Computer, Music, Working, Studies, Life...</h1>
							<p>Not a man to waste words! Let's see what I've got here!</p>
						</div>
					</div>
				</div>					
				<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="single-other-issue">
							<div class="thumb">
								<img class="img-fluid" style="width: 245; height: 155px; object-fit: cover; " src="{% static 'images/amir_darabi.jpg' %}" alt="">					
							</div>
							<a href="{% url 'website:detailed_about' cat_name='music'  %}">
								<h4>Music</h4>
							</a>
							<p>
								Well I'm really into music and believe it or not if I could feel safe living a musician life, I would've put all of my effort only in this field.
							</p>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="single-other-issue">
							<div class="thumb">
								<img style="height: 80%; object-fit: cover;" class="img-fluid" src="{% static 'images/_4th_cover.png' %}" alt="">					
							</div>
							<a href="{% url 'website:detailed_about' cat_name='programming' %}">
								<h4>Programming and Projects</h4>
							</a>
							<p>
								I'm really into Django and Python these days. So eager to learn looking for a good path to grow! 
							</p>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="single-other-issue">
							<div class="thumb">
								<img class="img-fluid" src="{% static 'images/life.jpg' %}" alt="">					
							</div>
							<a href="{% url 'website:detailed_about' cat_name='life' %}">
								<h4>Life is not Beautiful!</h4>
							</a>
							<p>
								It's a meaningless life no matter you are Maziar or Steve Jobs. So what the heck am I doning here palnning and learning skills? For what?!
							</p>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="single-other-issue">
							<div class="thumb">
								<img class="img-fluid" src="{% static 'images/daneshgah.jpg' %}" alt="">					
							</div>
							<a href="{% url 'website:detailed_about' cat_name='studies' %}">
								<h4>University</h4>
							</a>
							<p>
								I'm studying Computer Engineering at Shiraz University of Technology, I don't really have good memories of studying but again Life goes on!
							</p>
						</div>
					</div>																		
				</div>
			</div>	
		</section>
		<!-- End other-issue Area -->
		

	
		<!-- Start home-about Area -->
		<section class="home-about-area">
			<div class="container-fluid">
				<div class="row align-items-center justify-content-end">
					<div class="col-lg-6 col-md-12 home-about-left">
						<h1>
							You don't still Know what you're doing here? <br>
							Feel free to talk to me! <br>
							We‘ll keep in touch darling!
						</h1>
						<p>
							There two main reasons for this website.<br>First, well this website is mainly about me(Maziar!) and i want to share and annonce the fields I'm interested in and how good I am in those fields. <br> 
							 Second, to gather the music lovers into a nice and original musical environment where everyone can share their thoughts, feelings and find new freinds! 
							
						</p>
						<a href="{% url 'website:contact' %}" class="primary-btn text-uppercase">Lets Contact!</a>
					</div>
					<div class="col-lg-6 col-md-12 home-about-right no-padding">
						<img  class="img-fluid" src="{% static 'images/aria_karimi.jpg' %}" alt="">
					</div>
				</div>
			</div>	
		</section>
		<!-- End home-about Area -->
		

		
<section class="recent-blog-area section-gap" >
    <div class="container" >
        <div class="row d-flex justify-content-center" style="margin-top:0px ;">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Lets get to Know our Cool members!</h1>
                    <p>By following our friends you would get notified whenever they have a new post</p>
                </div>
            </div>
        </div>							
        <div class="row">
            <div class="active-recent-blog-carusel">
                {% for profile in random_profiles %}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img class="img-fluid" style="border-radius: 50%; width: 140px; height: 140px; object-fit: cover;" src="{{profile.profile_image.url}}" alt="">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                <li>
									{% if request.user.is_authenticated %}
										<form method="post" action="">
												{% csrf_token %}
												<input type="hidden" name="target_profile_id" value="{{ profile.id }}">
													{% if profile in request.user.profile.follows.all %}
													<button class="main__user-suggestion__follow-btn" type="submit">Following</button>
												{% else %}
												<button class="main__user-suggestion__follow-btn" type="submit">Follow</button>
												{% endif %}
										</form>
										<li>
											<a href="{% url 'blog:blog_author' profile.user.username %}">View the Posts</a>
										</li>	
									{% else %}
									<a href="{% url 'login' %}" >Follow </a>	
                                </li>
                                <li>
                                    <a href="{% url 'blog:blog_author' profile.user.username %}">View the Posts</a>
                                </li>	
								{% endif %}										
                            </ul>
                        </div>
                        <a href="{% url 'blog:blog_author' profile.user.username %}"><h4 class="title">{{profile.user.username}}</h4></a>
                        <p>
                            {{profile.bio|truncatewords:17}}
                        </p>
                    </div>	
                </div>
                {% endfor %}
                                                    

            </div>
        </div>
    </div>	
</section>


		
	
	{% endblock %}	

		