MuzMusic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from .error_views import handler404, handler500, handler400, handler403  # Import directly from the main project



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('account.urls')),


]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)






# handler404 = handler404  # Set the error handlers
# handler500 = handler500
# handler400 = handler400
# handler403 = handler403

blog/urls.py
from django.urls import path
from .views import BlogSingleView,BasePostListView,BlogAuthorView,BlogCategoryView,BlogHomeView,likeView,PostCreateView,follow_unfollow

app_name='blog'

urlpatterns = [
   # path('',BlogView.as_view(),name='blog_view'),
    path('single-view/<int:pk>',BlogSingleView.as_view(), name='single_view'),
    path('category/<str:cat_name>/', BlogCategoryView.as_view(), name='blog_category'),
    path('author/<str:author_name>/', BlogAuthorView.as_view(), name='blog_author'),
    path('', BlogHomeView.as_view(), name='blog_home'),
        # This will handle the default case with pagination
    path('like/<int:pk>',likeView, name='like_post'),
    path('post-create',PostCreateView.as_view(),name='post_create'),
    path('follow-unfollow',follow_unfollow,name='follow')
   ]

blog/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.urls import reverse



class Category(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    category_image= models.ImageField(default='default_profile.png')
    def __str__(self):
        return self.slug
    

class Post(models.Model):
    title= models.CharField(max_length=100)
    content=models.TextField()
    category=models.ManyToManyField(Category)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    image_file=models.ImageField()
    audio_file = models.FileField(null=True,blank=True)
    counted_views = models.IntegerField(default=1)
    post_author=models.ForeignKey(User,on_delete=models.CASCADE)
    likes=models.ManyToManyField(User,related_name='post_likes',null=True,blank=True)

    def total_likes(self):
       return self.likes.count()

    def get_absolute_url(self):
       return reverse('blog:single_view',kwargs={'pk':self.id})

    # This is new!
    def clean(self):
        if (not self.image_file and not self.audio_file and not self.content):
            raise ValidationError("Either content or image of audio must have a value.")

        super().clean()

    
    def __str__(self):
        return str(self.id) +':'+ self.title 
    

class Comment(models.Model):
  comment_author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=False)
  post=models.ForeignKey(Post,on_delete=models.CASCADE)
  content = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  def __str__(self):
    try:
      return f'{self.comment_author.username} : {self.content[:40]}'
    except:
      return f'no author : {self.content[:30]}'
    
  

blog/forms.py
from django import forms
from .models import Post,Category,Comment



class PostCreateForm(forms.ModelForm):
    category= forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['title', 'post_author', 'category', 'content', 'image_file', 'audio_file']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }


 
class PostEditForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','post_author','category','content','image_file','audio_file']

        widgets = {
            'title':forms.TextInput(attrs={'class': 'form-control'}),
            'title_tag':forms.TextInput(attrs={'class': 'form-control'}),
            'content':forms.Textarea(attrs={'class': 'form-control'}),

        }
 

class FollowForm(forms.Form):
    target_profile_id = forms.IntegerField(widget=forms.HiddenInput())


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content','post','comment_author']
        widgets = {
            'content':forms.Textarea(attrs={'class':'form-control mb-10','placeholder':'Share your thoughts...'})
        }

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,FormView
from .models import Post,Comment
from django.db.models import Q,F
from account.models import Profile
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import PostCreateForm,CommentForm
from django.utils.safestring import mark_safe
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail,EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from decouple import config



class BasePostListView(ListView):
    model = Post
    paginate_by = 5  # Default pagination
    context_object_name='posts'
    ordering=['-id']

    def get_queryset(self):
        queryset = super().get_queryset()  # Retrieve all posts by default
        
        # Get the search query from GET parameters
        search_query = self.request.GET.get('search', '')
        if search_query:
            # Filter posts based on title, content, or author's username
            queryset = queryset.filter(
                Q(title__icontains=search_query) |
                Q(content__icontains=search_query) |
                Q(post_author__username__icontains=search_query)
            )
        

           # Filter by category if provided
        cat_name = self.kwargs.get('cat_name')
        if cat_name:
            queryset = queryset.filter(category__slug=cat_name)
        # Filter by author if provided
        author_name = self.kwargs.get('author_name')
        if author_name:
            queryset = queryset.filter(post_author__username=author_name)
        return queryset
  


class BlogCategoryView(LoginRequiredMixin,BasePostListView):
    template_name = 'blog/blog-home.html'
    
    def get_queryset(self):
        return super().get_queryset()  # Calls the base logic to filter by category

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        return context

class BlogAuthorView(LoginRequiredMixin,BasePostListView):
    template_name = 'blog/blog-author.html'
    
    def get_queryset(self):
        return super().get_queryset()  # Calls the base logic to filter by author
    
    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
    
        username=self.kwargs['author_name']
        profile=get_object_or_404(Profile,user__username=username)
        following=profile.follows.all().exclude(user__username=username)
        followed=profile.followed_by.all().exclude(user__username=username)
        context['username']=username
        context['following']=following
        context['followed']=followed
        context['profile']=profile
        return context



class BlogHomeView(BasePostListView):
    template_name = 'blog/blog-home.html'  # Specify the template for the main blog view




class BlogSingleView(LoginRequiredMixin,DetailView):
    model=Post 
    template_name='blog/blog-single.html'
    context_object_name='post'   

    def get_context_data(self,**kwargs):
        context= super().get_context_data(**kwargs)
        Post.objects.filter(id=self.kwargs.get('pk')).update(counted_views=F('counted_views') + 1)
        post_tobe_liked=get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes=post_tobe_liked.total_likes()
        post = self.get_object()
        post_author=Profile.objects.get(user=post.post_author)
        comments = Comment.objects.filter(post=post).order_by('-created')
        
        form=CommentForm()
        liked=False
        if post_tobe_liked.likes.filter(id=self.request.user.id).exists():
            liked=True
        context['liked']=liked
        context['total_likes']=total_likes    
        context['comments'] = comments  # Add the comments to the context
        context['form']=form
        context['profile']=post_author
        print(post_author)
        return context  
    

        # if you use get instead of filter you are encountring an error! = > AttributeError at /blog/single-view/1
        # 'Post' object has no attribute 'update'

        # this was a solution!
        # post=Post.objects.get(id=self.kwargs.get('pk'))
        # post.counted_views +=1
        # post.save()
    def post(self, request, *args, **kwargs):
            form = CommentForm(request.POST)
            if form.is_valid():
                form.save()
                # sometimes i dont understand difference between the obj and its id
                return HttpResponseRedirect(reverse('blog:single_view',kwargs={'pk':self.get_object().id}))

            return self.get(request, *args, **kwargs)
       

# i dont like this func, i am feeling some code smell
# follwing and unfollowing
# i was a method in the account app, i didint even change the name so that i know there is code smell
# @login_required(login_url='account/login')
# def members_profile(request):
#         if request.method == 'POST':
#             current_user_profile=request.user.profile
#             action=request.POST['follow']
#             target_profile=request.POST['target_profile']
#             print(action)
#             if action == 'unfollow':
#                 current_user_profile.follows.remove(target_profile)
#             else:
#                 current_user_profile.follows.add(target_profile
#             current_user_profile.save()    
#             return HttpResponseRedirect(reverse('blog:blog_author',kwargs={'author_name':s}))        


class PostCreateView(LoginRequiredMixin,CreateView):
    template_name='blog/create-post.html'
    model=Post
    # fields=['title','post_author','category','content','image_file','audio_file']
    form_class = PostCreateForm

    
    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['data'] = {'post_author': self.request.user}  # Set the default value for post_author field
    #     return kwargs

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST,request.FILES)
        if form.is_valid():
            post_author=form.cleaned_data['post_author']
            followed_by=post_author.profile.followed_by.all().exclude(pk=post_author.pk)
            email_list = [follower.user.email for follower in followed_by]
            # email_list = []
            # for e in followed_by:
            #     email_list.append(e.user.email)



                # The ','.join() function takes a list of strings as an argument and concatenates
                # them into a single string. It places a specified string separator (in this case, a comma ,) 
                # between each pair of adjacent strings.
            form.save()
            post_id = post_author.username

            post_url = f'https://muzmusic.ir/blog/author/{post_id}'
            link = f'{post_author.username} has a new post! <a href="{post_url}">Let\'s check it out!</a>'
            html_message = f'{link}'

            # Strip HTML tags to create a plain text version
            plain_message = strip_tags(html_message)

            # Create the email message
            email = EmailMultiAlternatives(
                subject='New Notification from MuzMusic',
                body=plain_message,  # Plain text version
                from_email=config('EMAIL'),
                to=email_list,
            )

# Attach the HTML version
            email.attach_alternative(html_message, "text/html")

# Send the email
            email.send()


        else:
             for field, errors in form.errors.items():
                messages.add_message(request, messages.ERROR,mark_safe( f"Field {field} has the following errors: {errors}"))
        return redirect('blog:blog_home')
        # actually i want to return the user the sigle page of the post but i cant!



def likeView(request,pk):
    post=get_object_or_404(Post,id=pk)

    liked =False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked=False
    else:
        post.likes.add(request.user)
        liked=True
    return HttpResponseRedirect(reverse('blog:single_view',kwargs={'pk':pk}))        




# def follow_view(request,pk):
#     current_user_id=request.user.id
#     current_profile_id=pk
#     follow_unfollow(current_user_id,current_profile_id)
#     return HttpResponseRedirect(reverse('blog:author_view', ))
def follow_unfollow(request):
    if request.method == 'POST':
        target_profile=Profile.objects.get(user__username=request.POST.get('target_profile'))
        current_user_profile=Profile.objects.get(user__username=request.POST.get('user_id'))
        print(current_user_profile,target_profile)
        action = current_user_profile.follows.filter(id=target_profile.id).exists()

        if action:
            print('remove')
            current_user_profile.follows.remove(target_profile.id)
        else:
            print('add')
            current_user_profile.follows.add(target_profile.id)

        return redirect(request.META.get('HTTP_REFERER', '/default_redirect_url/'))

templates/blog/ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'images/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/blog-author.html
{% extends 'base.html' %}
{% load static %}
{% load blog_custom_tags %}
{% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							{% if request.user.username == username %}
							<h1 class="text-white">
								Welcome to your Personal page Dear {{request.user.username}}
							</h1>	
							{% else %}
							<h1 class="text-white">
								Welcome to {{username}}'s Personal page
							</h1>	
							{% endif %}
							<p class="text-white">
								Come on dude, lets some friends and share our thoughts and off course music!
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  



			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<!-- this is left for the style of the page -->
			</section>
			<!-- End top-category-widget Area -->


			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
						{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'blog:blog_category' cat.slug %}">
											{{cat.title}}
											{% if not forloop.last %}
											,
											{% endif %}	
										</a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' post.post_author %}">{{post.post_author.username}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.created|timesince}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{post.comment_set.count}}</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image_file.url}}" alt="">
									</div>
									<a class="posts-title" href="{{post.get_absolute_url}}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content}}
									</p>
								</div>
							</div>
						{% endfor %}
						














						{% if no_results_message %}
						<div class="single-post row">
							<div class="col-lg-3  col-md-3 meta-details">
								<ul class="tags">
									{% for cat in post.category.all %}
									<li><a href="#">
										{{cat.title}}
										{% if not forloop.last %}
										,
										{% endif %}	
									</a></li>
									{% endfor %}
								</ul>
							
							</div>
							<div class="col-lg-9 col-md-9 ">
								<div class="feature-img">
									<img class="img-fluid" src="{% static 'images/not_found.jpg' %}" alt="">
								</div>
								<a class="posts-title" href="{{post.get_absolute_url}}"><h3>{{ no_results_message }}</h3></a>
								<p class="excert">
									We did our best nothing can suit your search, Please choose more accurate keywords!
								</p>
								<a href="{% url 'blog:blog_view' %}" class="primary-btn">Go Back</a>
							</div>
						</div>
						{% endif %}







						{% categories_list  %}



					{% if is_paginated %}			
					<nav class="blog-pagination justify-content-center d-flex">
						<ul class="pagination">
							{% if page_obj.has_previous %}
							<li class="page-item">
								<a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-left"></span>
									</span>
								</a>
							</li>
							{% endif %}
	
							{% for i in page_obj.paginator.page_range %}
							<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
							{% endfor %}
	
							{% if page_obj.has_next %}
							<li class="page-item">
								<a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-right"></span>
									</span>
								</a>
							</li>
							{% endif %}
						</ul>
					</nav>
					{% endif %}






						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								<div class="single-sidebar-widget search-widget">
									<form class="search-form" action="">
			                            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
			                            <button type="submit"><i class="fa fa-search"></i></button>
			                        </form>
								</div>
								
								{% include 'account/writer-info.html' %}



								{% include 'blog/personal_page_info.html' %}	
						<!-- this tag is to load the list of the people the author follws and is followed by-->
								<!-- {% popular_posts %} -->
								{% include 'blog/ads.html' %}
								<!-- {% post_category %} -->
													
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
		{% endblock %}

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_custom_tags %}
{% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Let's Checkout some Posts!		
							</h1>	
							<p class="text-white">
									Lets forget the whole world and keep in touch with a backgound of light Music!
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  


			<section class="top-category-widget-area pt-90 pb-90 ">
				<!-- this is left for the style of the page -->
			</section>





		
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
						{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li><a href="{% url 'blog:blog_category' cat.slug %}">
											{{cat.title}}
											{% if not forloop.last %}
											,
											{% endif %}	
										</a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' post.post_author %}">{{post.post_author.username}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="{{post.get_absolute_url}}">{{post.created|timesince}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="{{post.get_absolute_url}}">{{post.counted_views}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="{{post.get_absolute_url}}">{{post.comment_set.count}}</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image_file.url}}" alt="">
									</div>
									<a class="posts-title" href="{{post.get_absolute_url}}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:21}}
									</p>
									<a href="{% url  'blog:blog_author' post.post_author %}" class="primary-btn">More form {{post.post_author.username}}</a>
								</div>
							</div>
						{% endfor %}
						











						{% categories_list  %}

						
					{% if is_paginated %}			
					<nav class="blog-pagination justify-content-center d-flex">
						<ul class="pagination">
							{% if page_obj.has_previous %}
							<li class="page-item">
								<a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-left"></span>
									</span>
								</a>
							</li>
							{% endif %}
	
							{% for i in page_obj.paginator.page_range %}
							<li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
							{% endfor %}
	
							{% if page_obj.has_next %}
							<li class="page-item">
								<a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-right"></span>
									</span>
								</a>
							</li>
							{% endif %}
						</ul>
					</nav>
					{% endif %}






						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								<div class="single-sidebar-widget search-widget">
									<form class="search-form" action="">
			                            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
			                            <button type="submit"><i class="fa fa-search"></i></button>
			                        </form>
								</div>
								
								{% popular_posts %}
								{% include 'blog/ads.html' %}
								{% post_category %}
													
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
		{% endblock %}

templates/blog/categories.html
	
{% load static %}

<section class="recent-blog-area section-gap" >
    <div class="container" >
        <div class="row d-flex justify-content-center" style="margin-top:0px ;">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Find Posts based on your Taste!</h1>
                    <p>Come on just click on your fovorite category</p>
                </div>
            </div>
        </div>							
        <div class="row">
            <div class="active-recent-blog-carusel">
                {% for category in categories %}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img class="img-fluid" style=" width: 160px; height: 160px; object-fit: cover;" src="{{category.category_image.url}}" alt="">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                
                                <li>
                                    <a href="{% url 'blog:blog_category' category %}">{{category.title}}</a>
                                </li>	
                            </ul>
                        </div>
                        <a href=""><h4 class="title">{{profile.user.username}}</h4></a>
                        <p>
                            {{profile.bio|slice:":40"}}
                        </p>
                    </div>	
                </div>
                {% endfor %}
                                                    

            </div>
        </div>
    </div>	
</section>

templates/blog/create-post.html
{% extends 'account/account_base.html' %}
{% load static %}

{% block content %}
<body style="background-color: #999999;">
	<div class="limiter">
		<div class="container-login100">
			<div class="login100-more"></div>
			<div class="wrap-login100 p-l-50 p-r-50 p-t-72 p-b-50">


				<form action="{% url 'blog:post_create' %}" method="POST" enctype="multipart/form-data" class="login100-form validate-form">
					{% csrf_token %}

                    <input type="hidden" name="post_author" value="{{request.user.id}}">
					<span class="login100-form-title p-b-59">
						Create Post
					</span>
					<!--
					<div class="wrap-input100 validate-input" >
						<span class="label-input100">First Name</span>
							{{form.first_name}}
						<span class="focus-input100"></span>
						</div>
						<div class="wrap-input100 validate-input" >
							<span class="label-input100">Last Name</span>
								{{form.last_name}}
							<span class="focus-input100"></span>
							</div>
						
						<div class="wrap-input100 validate-input" >
							<span class="label-input100">You could choose a profile picture</span>
							{{form.image}}
							<span class="focus-input100"></span>
						</div>

						-->
						
					<div class="wrap-input100 validate-input" data-validate="Username is required">
						<span class="label-input100">Title</span>
						{{form.title}}
						<span class="focus-input100"></span>
					</div>

                    <div class="wrap-input100 validate-input" >
                        <span class="label-input100">Category</span>
                            {{form.category}}
                        <span class="focus-input100"></span>
                        </div>
			
				
					
					<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
						<span class="label-input100">Content</span>
						{{form.content}}
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
						<span class="label-input100">Image</span>
						{{form.image_file}}
						<span class="focus-input100"></span>
					</div>

                    
					<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
						<span class="label-input100">Audio</span>
						{{form.audio_file}}
						<span class="focus-input100"></span>
					</div>




					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button type="submit" class="login100-form-btn">
								Publish
							</button>
						</div>
						<div class="alert alert-light" role="alert">
							{% if messages %}
							<ul class="messages">
								{% for message in messages %}
								<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
									<p>{{ message }}</p>
									</li>
									{% endfor %}
							</ul>
							{% endif %}
						</div>
					</div>


				</form>
			</div>
		</div>
	</div>

	{% endblock %}

templates/blog/popular-posts.html
{% load static %}


<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}

            <div class="single-post-list d-flex flex-row align-items-center">
                <div class="thumb">
                    <img class="img-fluid" src="{{post.image_file.url}}" alt="">
                </div>
                <div class="details">
                    <a href="{{post.get_absolute_url}}"><h6>{{post.title}}</h6></a>
                    <p>{{post.created|timesince}}</p>
                </div>
            </div>
        {% endfor %}
      								
    </div>
</div>

templates/blog/post-category.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
	<h4 class="category-title">Post Catgories</h4>
	<ul class="cat-list">
		{{s}}
		{% for cat,value in categories.items %}
			<li>
				<a href="{% url 'blog:blog_category' cat %}" class="d-flex justify-content-between">
					<p>{{cat}}</p>
					<p>{{value}}</p>
				</a>
			</li>
		{% endfor %}
														
	</ul>
</div>	